# Generated by Django 3.2.9 on 2021-11-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20211126_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('MULTY', 'Multi'), ('TEXT', 'Text')], max_length=10),
        ),
    ]
