# Generated by Django 3.2.9 on 2021-11-27 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20211127_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersurvey',
            old_name='question',
            new_name='survey',
        ),
    ]
